version: '3'

services:
    nginx: 
        image: nginx
        ports: 
            - "80:80"
        networks: 
            - my-network
        deploy:
            mode: replicated
            replicas: 3

networks:
    my-network:
        external: true
